image: Visual Studio 2017
version: '{branch}.{build}'

clone_folder: c:\projects\amqp

install:
  - ps: appveyor\install.ps1

cache:
  - c:\build-cache -> .appveyor.yml, appveyor\install.ps1

environment:
  BIN_SDK_VER: 2.2.0
  matrix:
    - PHP_VER: 7.4.4
      ARCH: x64
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.4.4
      ARCH: x64
      TS: 0
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.4.4
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.4.4
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.3.16
      ARCH: x64
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.3.16
      ARCH: x64
      TS: 0
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.3.16
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.3.16
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.2.29
      ARCH: x64
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.2.29
      ARCH: x64
      TS: 0
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.2.29
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0
    - PHP_VER: 7.2.29
      ARCH: x86
      TS: 1
      VC: vc15
      DEP: librabbitmq-0.9.0

build_script:
  - ps: appveyor\build.ps1

after_build:
  - ps: appveyor\package.ps1
