language: php

php:
  - 5.2
  - 5.3
  - 5.4

services:
  - rabbitmq

env:
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=master

before_script:
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && git submodule init && git submodule update"
  - sh -c "cd rabbitmq-c && autoreconf -i && ./configure && make && sudo make install"
  - sh -c "phpize && ./configure && make"

script:
  - sh -c "make test | tee result.txt"
  - sh test-report.sh
  - sh -c "grep -q FAILED result.txt; test $? -eq 0 && false || true"

notifications:
  email:
    - lstrojny@php.net
