language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

services:
  - rabbitmq

env:
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=master
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=v0.4.1
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=v0.4.0

before_script:
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && git submodule init && git submodule update"
  - sh -c "cd rabbitmq-c && autoreconf -i && ./configure && make && sudo make install"
  - sh -c "phpize && ./configure && make"

script:
  - sh -c "make test | tee result.txt"
  - sh test-report.sh

notifications:
  email:
    - lstrojny@php.net
    - bkw@codingforce.com
